export default {
  paramClientId: 1,
  accounts: [],
  interestRate: '',
  installment: '',
  annualRate: '',
  monthlyAmount: '',
  totalLoanAmount: '',
  loanCosts: '',
  percentageLoanCosts: '',
  cae: '',
  stampTax: '',
  notaryFee: '',
  monthlyRate: '',
  disgraceInsurance: '',
  unemploymentInsurance: '',
};
